version: '3.9-slim'

services:
  web:
    build: .
    command: gunicorn todo_api.wsgi:application --bind 0.0.0.0:8000
    environment:
      DB_NAME: shema_db
      DB_USER: shema
      DB_PASSWORD: secure_password
      DB_HOST: db
      DB_PORT: 2409
    ports:
      - "2410:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shema_db
      POSTGRES_USER: shema
      POSTGRES_PASSWORD: shema
    ports:
      - "2411:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "911:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
