- name: Deploy Docker Application
  hosts: target_server
  become: yes
  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /opt/todo_app
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Install Docker dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install Docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy project files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/"
        dest: /opt/todo_app/
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Start application with Docker Compose
      ansible.builtin.shell:
        cmd: docker-compose up -d
        chdir: /opt/todo_app
      become: yes
