- name: Deploy Docker Application
  hosts: target_server
  become: yes
  tasks:

    - name: Install Docker
      ansible.builtin.raw: |
        curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker Compose
      ansible.builtin.raw: |
        curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Log in to Docker Hub
      ansible.builtin.shell: |
        echo "{{ docker_hub_password }}" | docker login -u "{{ docker_hub_username }}" --password-stdin
      vars:
        docker_hub_username: "{{ lookup('env', 'DOCKER_HUB_USERNAME') }}"
        docker_hub_password: "{{ lookup('env', 'DOCKER_HUB_PASSWORD') }}"

    - name: Pull the latest Docker images
      ansible.builtin.shell: |
        cd /path/to/your/app
        docker-compose pull

    - name: Start the application using Docker Compose
      ansible.builtin.shell: |
        cd /path/to/your/app
        docker-compose up -d
